name: mav_msg
on: [push]

jobs:
  mav_msg:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Pull Mavlink Definitions
        run: git pull git@github.com:mavlink/mavlink.git && ls
