name: Publish packages

# Events that trigger this workflow
on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

jobs:
  publish:
    name: Publish packages to the GitHub Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Set up JDK 16 💿
        uses: actions/setup-java@v2.0.0
        with:
          distribution: 'zulu'
          java-version: '16'
          java-package: jdk

      - name: Restore cache release upload URL ♻️
        uses: actions/cache@v2.1.5
        with:
          path: ~/.build-env
          key: 'github-release-action'

      - name: Import environment
        run: cat ~/.build-env >> $GITHUB_ENV

      - name: Build version from tag
        run: |
          echo "version=${TAG:1}" >> $GITHUB_ENV
        env:
          TAG: ${{ env.tag }}

      - name: Publish packages 🗜
        run: chmod +x gradlew && ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.version }}
