name: Publish packages

# Events that trigger this workflow
on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

jobs:
  publish:
    name: Publish packages to the GitHub Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.3.4
        with:
          # enable when mavlink package is finished
          #submodules: 'recursive'

      - name: Set up JDK 16 💿
        uses: actions/setup-java@v2.0.0
        with:
          distribution: 'zulu'
          java-version: '16'
          java-package: jdk

      - name: Publish packages 🗜
        run: chmod +x gradlew && ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
